services:
  - type: web
    name: agenda-sql-app
    env: python
    buildCommand: ./render-build.sh
    startCommand: gunicorn app:app
    region: oregon
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10